# Define variables for the Application/Webserver instance Configuration
# Playbook Configuration
play_name   : Execute Shell Script from GitHub Repository
target_host : all
become_root : yes

# # Project Repository and Branch
# project_repository    : https://github.com/awanmbandi/aws-real-world-projects.git
# destination_clone_path: /home/ansible/ansible-tower-project
# project_repo_branch   : ansible-tower-workflow-project
# # clone_project_repo    : yes
# # update_project_repo   : yes

# Assign Execution Permission and Execute Script
assign_execute_permission: chmod +x /home/ansible/ansible-tower-project/startup-script/app-automation.sh
execute_automation_script: /home/ansible/ansible-tower-project/startup-script/app-automation.sh

